stages:
  measure-mind-val:
    cmd: python -m poprox_recommender.test_offline
    deps:
      - src/poprox_recommender/test_offline.py
      - data/MINDlarge_dev.zip
    outs:
      - outputs/user-metrics.csv.gz
    metrics:
      - outputs/metrics.json:
          cache: false
