vars:
  - pipelines:
      - nrms
      - softmax
      - nrms_rrf_static_user
      - nrms_topic_scores
      - nrms_topics_static

stages:
  # these are *foreach stages*: they have multiple versions, one for each pipeline.
  recommend-mind-val:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDlarge_dev -o outputs/mind-val/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDlarge_dev.db
      outs:
        - outputs/mind-val/${item}/recommendations.parquet
        - outputs/mind-val/${item}/recommendations.ndjson.zst
        - outputs/mind-val/${item}/embeddings.parquet
        - outputs/mind-val/${item}/generate-task.json

  measure-mind-val:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDlarge_dev mind-val ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDlarge_dev.db
        - outputs/mind-val/${item}/recommendations.parquet
      outs:
        - outputs/mind-val/${item}/recommendation-metrics.csv.gz
      metrics:
        - outputs/mind-val/${item}/metrics.json:
            cache: false

  recommend-mind-small:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev -o outputs/mind-small/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDsmall_dev.db
      outs:
        - outputs/mind-small/${item}/recommendations.parquet
        - outputs/mind-small/${item}/recommendations.ndjson.zst
        - outputs/mind-small/${item}/embeddings.parquet
        - outputs/mind-small/${item}/generate-task.json

  measure-mind-small:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-small ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDsmall_dev.db
        - outputs/mind-small/${item}/recommendations.parquet
      outs:
        - outputs/mind-small/${item}/recommendation-metrics.csv.gz
      metrics:
        - outputs/mind-small/${item}/metrics.json:
            cache: false

  # small subset for quick testing
  recommend-mind-subset:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev --subset=1000 -o outputs/mind-subset/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDsmall_dev.db
      outs:
        - outputs/mind-subset/${item}/recommendations.parquet
        - outputs/mind-subset/${item}/recommendations.ndjson.zst
        - outputs/mind-subset/${item}/embeddings.parquet
        - outputs/mind-subset/${item}/generate-task.json

  measure-mind-subset:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-subset ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDsmall_dev.db
        - outputs/mind-subset/${item}/recommendations.parquet
      outs:
        - outputs/mind-subset/${item}/recommendation-metrics.csv.gz
      metrics:
        - outputs/mind-subset/${item}/metrics.json:
            cache: false

  # real POPROX data snapshot
  recommend-poprox:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -P POPROX -o outputs/poprox/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/POPROX.db
      outs:
        - outputs/poprox/${item}/recommendations.parquet
        - outputs/poprox/${item}/recommendations.ndjson.zst
        - outputs/poprox/${item}/embeddings.parquet
        - outputs/poprox/${item}/generate-task.json

  recommend-poprox-latest:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -P POPROX --latest -o outputs/poprox-latest/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/POPROX.db
      outs:
        - outputs/poprox-latest/${item}/recommendations.parquet
        - outputs/poprox-latest/${item}/recommendations.ndjson.zst
        - outputs/poprox-latest/${item}/embeddings.parquet
        - outputs/poprox-latest/${item}/generate-task.json

  recommend-poprox-recent:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -P POPROX --recent -o outputs/poprox-recent/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/POPROX.db
      outs:
        - outputs/poprox-recent/${item}/recommendations.parquet
        - outputs/poprox-recent/${item}/recommendations.ndjson.zst
        - outputs/poprox-recent/${item}/embeddings.parquet
        - outputs/poprox-recent/${item}/generate-task.json

  measure-poprox:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -P POPROX poprox ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/POPROX.db
        - outputs/poprox/${item}/recommendations.parquet
      outs:
        - outputs/poprox/${item}/recommendation-metrics.csv.gz
      metrics:
        - outputs/poprox/${item}/metrics.json:
            cache: false

  collect-metrics:
    foreach:
      - mind-subset
      - mind-small
      - mind-val
    do:
      cmd: python -m poprox_recommender.evaluation.collect ${item}
      deps:
        - src/poprox_recommender/evaluation/collect.py
        - outputs/${item}/
      outs:
        - outputs/${item}-recommendation-metrics.csv.gz
        - outputs/${item}-metrics.csv:
            cache: false
        - outputs/${item}-tasks.csv:
            cache: false
