vars:
  - pipelines:
      - nrms
      - mmr
      - pfar
      - softmax
      - topic_cali
      - nrms_rrf_static_user
      - nrms_topic_scores
      - nrms_topics_static
      - nrms_images

stages:
  # these are *foreach stages*: they have multiple versions, one for each pipeline.
  recommend-mind-val:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDlarge_dev -o outputs/mind-val/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDlarge_dev.zip
      outs:
        - outputs/mind-val/${item}/recommendations.parquet
        - outputs/mind-val/${item}/recommendations.ndjson.zst
        - outputs/mind-val/${item}/embeddings.parquet
        - outputs/mind-val/${item}/generate-task.json

  measure-mind-val:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDlarge_dev mind-val ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDlarge_dev.zip
        - outputs/mind-val/${item}/recommendations.parquet
      outs:
        - outputs/mind-val/${item}/profile-metrics.csv.gz
      metrics:
        - outputs/mind-val/${item}/metrics.json:
            cache: false

  recommend-mind-small:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev -o outputs/mind-small/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDsmall_dev.zip
      outs:
        - outputs/mind-small/${item}/recommendations.parquet
        - outputs/mind-small/${item}/recommendations.ndjson.zst
        - outputs/mind-small/${item}/embeddings.parquet
        - outputs/mind-small/${item}/generate-task.json

  measure-mind-small:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-small ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDlarge_dev.zip
        - outputs/mind-small/${item}/recommendations.parquet
      outs:
        - outputs/mind-small/${item}/profile-metrics.csv.gz
      metrics:
        - outputs/mind-small/${item}/metrics.json:
            cache: false

  # small subset for quick testing
  recommend-mind-subset:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev --subset=1000 -o outputs/mind-subset/${item} ${item}
      deps:
        - src/poprox_recommender/evaluation/generate/
        - src/poprox_recommender/recommenders/configurations/${item}.py
        - models/nrms-mind/
        - data/MINDsmall_dev.zip
      outs:
        - outputs/mind-subset/${item}/recommendations.parquet
        - outputs/mind-subset/${item}/recommendations.ndjson.zst
        - outputs/mind-subset/${item}/embeddings.parquet
        - outputs/mind-subset/${item}/generate-task.json

  measure-mind-subset:
    foreach: ${pipelines}
    do:
      cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-subset ${item}
      deps:
        - src/poprox_recommender/evaluation/evaluate.py
        - src/poprox_recommender/evaluation/metrics/
        - data/MINDlarge_dev.zip
        - outputs/mind-subset/${item}/recommendations.parquet
      outs:
        - outputs/mind-subset/${item}/profile-metrics.csv.gz
      metrics:
        - outputs/mind-subset/${item}/metrics.json:
            cache: false

  collect-metrics:
    foreach:
      - mind-subset
      - mind-small
      - mind-val
    do:
      cmd: python -m poprox_recommender.evaluation.collect ${item}
      deps:
        - src/poprox_recommender/evaluation/collect.py
        - outputs/${item}/
      outs:
        - outputs/${item}-profile-metrics.csv.gz
        - outputs/${item}-metrics.csv:
            cache: false
