stages:
  recommend-mind-val:
    cmd: python -m poprox_recommender.evaluation.generate -M MINDlarge_dev -o outputs/mind-val
    deps:
      - src/poprox_recommender/evaluation/generate/
      - data/MINDlarge_dev.zip
    outs:
      - outputs/mind-val/recommendations
      - outputs/mind-val/embeddings.parquet

  measure-mind-val:
    cmd: python -m poprox_recommender.evaluation.evaluate -M MINDlarge_dev mind-val
    deps:
      - src/poprox_recommender/evaluation/evaluate.py
      - data/MINDlarge_dev.zip
      - outputs/mind-val/recommendations
    outs:
      - outputs/mind-val/mind-val-user-metrics.csv.gz
    metrics:
      - outputs/mind-val-metrics.csv:
          cache: false

  recommend-mind-small:
    cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev -o outputs/mind-small
    deps:
      - src/poprox_recommender/evaluation/generate/
      - data/MINDsmall_dev.zip
    outs:
      - outputs/mind-small/recommendations
      - outputs/mind-small/embeddings.parquet
  measure-mind-small:
    cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-small
    deps:
      - src/poprox_recommender/evaluation/evaluate.py
      - data/MINDlarge_dev.zip
      - outputs/mind-small/recommendations
    outs:
      - outputs/mind-small/mind-small-user-metrics.csv.gz
    metrics:
      - outputs/mind-small-metrics.csv:
          cache: false

  # small subset for quick testing
  recommend-mind-subset:
    cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev --subset=1000 -o outputs/mind-subset
    deps:
      - src/poprox_recommender/evaluation/generate/
      - data/MINDsmall_dev.zip
    outs:
      - outputs/mind-subset/recommendations
      - outputs/mind-subset/embeddings.parquet
  measure-mind-subset:
    cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-subset
    deps:
      - src/poprox_recommender/evaluation/evaluate.py
      - data/MINDlarge_dev.zip
      - outputs/mind-subset/recommendations.parquet
    outs:
      - outputs/mind-subset/mind-subset-user-metrics.csv.gz
    metrics:
      - outputs/mind-subset-metrics.csv:
          cache: false
