stages:
  recommend-mind-val:
    cmd: python -m poprox_recommender.evaluation.generate -M MINDlarge_dev -o outputs/mind-val-recommendations.duckdb
    deps:
      - src/poprox_recommender/evaluation/generate.py
      - data/MINDlarge_dev.zip
    outs:
      - outputs/mind-val-recommendations.duckdb

  measure-mind-val:
    cmd: python -m poprox_recommender.evaluation.evaluate -M MINDlarge_dev mind-val
    deps:
      - src/poprox_recommender/evaluation/evaluate.py
      - data/MINDlarge_dev.zip
      - outputs/mind-val-recommendations.duckdb
    outs:
      - outputs/mind-val-user-metrics.csv.gz
    metrics:
      - outputs/mind-val-metrics.csv:
          cache: false

  recommend-mind-small:
    cmd: python -m poprox_recommender.evaluation.generate -M MINDsmall_dev -o outputs/mind-small-recommendations.duckdb
    deps:
      - src/poprox_recommender/evaluation/generate.py
      - data/MINDsmall_dev.zip
    outs:
      - outputs/mind-small-recommendations.duckdb
  measure-mind-small:
    cmd: python -m poprox_recommender.evaluation.evaluate -M MINDsmall_dev mind-small
    deps:
      - src/poprox_recommender/evaluation/evaluate.py
      - data/MINDlarge_dev.zip
      - outputs/mind-small-recommendations.duckdb
    outs:
      - outputs/mind-small-user-metrics.csv.gz
    metrics:
      - outputs/mind-small-metrics.csv:
          cache: false
