stages:
  measure-mind-val:
    cmd: python -m poprox_recommender.evaluation.offline
    deps:
      - src/poprox_recommender/evaluation/offline.py
      - data/MINDlarge_dev.zip
    outs:
      - outputs/user-metrics.csv
    metrics:
      - outputs/metrics.json:
          cache: false
