[random]
seed = 20250612

[machines.screamer]
description = "INERTIAL GPU workstation"
idle_watts = 81

[machines.screamer.power_queries]
system = 'sum_over_time((apcupsd_nominal_power_watts{{machine="{machine}"}} * (apcupsd_ups_load_percent{{machine="{machine}"}} / 100))[{elapsed}ms:1s])'
cpu = 'delta(node_rapl_package_joules_total{{machine="{machine}"}}[{elapsed}ms:1s])'
gpu = 'sum_over_time((nvidia_gpu_power_usage_milliwatts{{machine="{machine}"}} / 1000)[{elapsed}ms:1s])'

[machines.cruncher]
description = "INERTIAL datacenter machine"
idle_watts = 220

[machines.cruncher.power_queries]
system = 'sum_over_time(sum(redfish_psu_input_power_watts{{machine="{machine}"}})[{elapsed}ms:1s])'
cpu = 'delta(sum(node_rapl_package_joules_total{{machine="{machine}"}})[{elapsed}ms:1s])'
gpu = 'delta(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{{machine="{machine}"}}[{elapsed}ms:1s]) / 1000'
