useDotenv: true

service: poprox-default-recommender
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048
  ephemeralStorageSize: 2048
  timeout: 25

  iam:
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - "logs:*"
          Resource: "*"

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      poprox-recommender:
        path: "./"

plugins:
  - serverless-offline
custom:
  "offline:true": # offline enabled parameters
    enabled: true
    filePrefix: "offline."
  "offline:false": # offline disabled parameters
    enabled: false
    filePrefix: ""
  offline: ${self:custom.offline:${strToBool(${env:IS_OFFLINE, false})}}

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

functions:
  # if offline mode enabled filePrefix = 'offline.' else filePrefix = ''
  ${file(./serverless/${self:custom.offline.filePrefix}functions.yaml):functions}
