useDotenv: true

service: poprox-default-recommender
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048 # 2gb
  timeout: 25
  architecture: x86_64

  iam:
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - "logs:*"
          Resource: "*"

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      poprox-recommender:
        path: "./"
        platform: linux/amd64

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

functions:
  generateRecommendations:
    image:
      name: poprox-recommender
    memorySize: 4096
    ephemeralStorageSize: 2048
    events:
      - httpApi:
          path: /
          method: post
