useDotenv: true

service: poprox-default-recommender

provider:
  name: aws
  runtime: python3.11
  profile: admin
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048 # 2gb
  timeout: 25
  architecture: x86_64
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

  iam:
    role:
      # Add statements to the IAM role to give permissions to Lambda functions
      statements:
        - Effect: Allow
          Action:
            - "logs:*"
          Resource: "*"

  ecr:
    # Using the pre-built image from ECR instead of building locally
    images:
      poprox-recommender:
        uri: 787842565111.dkr.ecr.us-east-1.amazonaws.com/serverless-poprox-default-recommender-prod:latest

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

functions:
  generateRecommendations:
    image:
      name: poprox-recommender
    memorySize: 4096
    ephemeralStorageSize: 2048
    events:
      - httpApi:
          path: /warmup
          method: get
      - httpApi:
          path: /
          method: post
