useDotenv: true

service: poprox-default-recommender
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  versionFunctions: false
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  memorySize: 2048 # 2gb
  timeout: 25
  architecture: x86_64

  iam:
    role: arn:aws:iam::${AWS::AccountId}:role/poprox-recommender-${AWS::Region}-lambdaRole-${opt:stage}

  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      poprox-recommender:
        path: "./"
        platform: linux/amd64

plugins:
  - serverless-offline
custom:
  "offline:true": # offline enabled parameters
    enabled: true
    filePrefix: "offline."
  "offline:false": # offline disabled parameters
    enabled: false
    filePrefix: ""
  offline: ${self:custom.offline:${strToBool(${env:IS_OFFLINE, false})}}

package:
  patterns:
    - "!venv/**"
    - "!models/**"
    - "!node_modules/**"
    - "!tests/**"
    - "**.py"
    - "**.html"

# if offline mode enabled filePrefix = 'offline.' else filePrefix = ''
functions: ${file(./serverless/${self:custom.offline.filePrefix}functions.yaml):functions}
