stages:
  results-mind-val:
    cmd: jupytext --to notebook --execute mind-val.md
    deps:
      - mind-val.md
      - ../outputs/mind-val/user-metrics.csv.gz
    outs:
      - mind-val.ipynb:
          cache: false

  results-mind-small:
    cmd: jupytext --to notebook --execute mind-small.md
    deps:
      - mind-small.md
      - ../outputs/mind-small/user-metrics.csv.gz
    outs:
      - mind-small.ipynb:
          cache: false
