name: Validate Source

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-pre-commit:
    name: Check that the pre-commit hooks have run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pre-commit
        run: |
          pipx install pre-commit

      - name: Install pre-commit hooks
        run: |
          pre-commit install-hooks

      - name: Check source repo
        run: |
          if pre-commit run --all-files; then
            echo "::notice title=pre-commit::pre-commit checks passed"
          else
            echo "::error title=pre-commit::committed code does not cleanly pass pre-commit"
            exit 1
          fi
