name: Test Docker

on:
  push:
    branches:
      - main
  pull_request:

# override default shell for mamba activation
defaults:
  run:
    shell: bash -el {0}

jobs:
  test-docker:
    name: Build and test Docker image
    runs-on: ubuntu-latest
    env:
      UV_LOCKED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🕶️ Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: 📦 Set up dependencies
        run: uv sync --no-default-groups --group=test --group=data --group=cpu

      - name: Show DVC config
        run: dvc config --list

      - name: Cache model data
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: docker-dvc-cache-${{ hashFiles('models/**.dvc', 'tests/**.dvc') }}

      - name: Fetch model and test data
        run: ./scripts/fetch-shared-data.sh
        env:
          GH_EVT: ${{github.event_name}}
          GH_REPO: ${{github.repository}}
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Build Docker image
        run: |
          docker build -t poprox-recommender:ci --build-arg LOG_LEVEL=DEBUG .

      - name: Start Docker container
        run: |
          docker run -d -p 9000:8080 --name=poprox-recommender poprox-recommender:ci

      - name: Run web service tests
        run: |
          uv run --no-sync pytest -v tests/web_service
        env:
          POPROX_TEST_TARGET: docker
          POPROX_TEST_PORT: 9000
          POPROX_CI_WITHOUT_MIND: 1

      - name: Run integration tests
        run: |
          uv run --no-sync pytest -v tests/integration
        env:
          POPROX_TEST_TARGET: docker
          POPROX_TEST_PORT: 9000

      - name: Dump Docker logs
        if: always()
        run: |
          docker logs poprox-recommender

      - name: Tear down Docker
        if: always()
        run: |
          docker stop poprox-recommender
          docker rm poprox-recommender
          docker image rm poprox-recommender:ci
